2023/07/24 20:27:58 [error] 1350#1350: *110 upstream prematurely closed connection while reading response header from upstream, client: 172.21.0.1, server: adduser.myapp.com, request: "POST / HTTP/1.1", upstream: "http://172.21.0.4:8089/v1/Adduser", host: "adduser.myapp.com"
2023/07/24 20:30:47 [error] 213#213: *4 upstream prematurely closed connection while reading response header from upstream, client: 172.21.0.1, server: adduser.myapp.com, request: "POST / HTTP/1.1", upstream: "http://172.21.0.4:8089/v1/Adduser", host: "adduser.myapp.com"
2023/07/24 21:09:44 [error] 210#210: *6 upstream prematurely closed connection while reading response header from upstream, client: 172.21.0.1, server: adduser.myapp.com, request: "POST / HTTP/1.1", upstream: "http://172.21.0.6:8089/v1/Adduser", host: "adduser.myapp.com"
2023/07/24 21:41:12 [error] 211#211: *10 upstream prematurely closed connection while reading response header from upstream, client: 172.21.0.1, server: adduser.myapp.com, request: "POST / HTTP/1.1", upstream: "http://172.21.0.6:8089/v1/Adduser", host: "adduser.myapp.com"
2023/07/26 11:22:32 [error] 216#216: *7 upstream prematurely closed connection while reading response header from upstream, client: 172.21.0.1, server: adduser.myapp.com, request: "POST / HTTP/1.1", upstream: "http://172.21.0.6:8089/v1/Adduser", host: "adduser.myapp.com"
2023/07/26 11:23:29 [error] 216#216: *15 upstream prematurely closed connection while reading response header from upstream, client: 172.21.0.1, server: adduser.myapp.com, request: "POST / HTTP/1.1", upstream: "http://172.21.0.6:8089/v1/Adduser", host: "adduser.myapp.com"
2023/07/26 11:24:03 [error] 216#216: *13 upstream prematurely closed connection while reading response header from upstream, client: 172.21.0.1, server: adduser.myapp.com, request: "POST / HTTP/1.1", upstream: "http://172.21.0.6:8089/v1/Adduser", host: "adduser.myapp.com"
2023/07/26 12:21:05 [warn] 233#233: *1 using uninitialized "upstream_authelia" variable, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", host: "adduser.myapp.com"
2023/07/26 12:21:05 [error] 233#233: *1 invalid URL prefix in "", client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", host: "adduser.myapp.com"
2023/07/26 12:21:05 [error] 233#233: *1 auth request unexpected status: 500, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", host: "adduser.myapp.com"
2023/07/26 12:21:18 [warn] 234#234: *2 using uninitialized "upstream_authelia" variable, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", host: "adduser.myapp.com"
2023/07/26 12:21:18 [error] 234#234: *2 invalid URL prefix in "", client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", host: "adduser.myapp.com"
2023/07/26 12:21:18 [error] 234#234: *2 auth request unexpected status: 500, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", host: "adduser.myapp.com"
2023/07/26 12:21:19 [warn] 233#233: *6 using uninitialized "upstream_authelia" variable, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", host: "adduser.myapp.com"
2023/07/26 12:21:19 [error] 233#233: *6 invalid URL prefix in "", client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", host: "adduser.myapp.com"
2023/07/26 12:21:19 [error] 233#233: *6 auth request unexpected status: 500, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", host: "adduser.myapp.com"
2023/07/26 12:21:19 [warn] 233#233: *7 using uninitialized "upstream_authelia" variable, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", host: "adduser.myapp.com"
2023/07/26 12:21:19 [error] 233#233: *7 invalid URL prefix in "", client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", host: "adduser.myapp.com"
2023/07/26 12:21:19 [error] 233#233: *7 auth request unexpected status: 500, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", host: "adduser.myapp.com"
2023/07/26 12:21:19 [warn] 233#233: *8 using uninitialized "upstream_authelia" variable, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", host: "adduser.myapp.com"
2023/07/26 12:21:19 [error] 233#233: *8 invalid URL prefix in "", client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", host: "adduser.myapp.com"
2023/07/26 12:21:19 [error] 233#233: *8 auth request unexpected status: 500, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", host: "adduser.myapp.com"
2023/07/26 12:23:36 [warn] 233#233: *28 using uninitialized "upstream_authelia" variable, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", host: "adduser.myapp.com"
2023/07/26 12:23:36 [error] 233#233: *28 invalid URL prefix in "", client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", host: "adduser.myapp.com"
2023/07/26 12:23:36 [error] 233#233: *28 auth request unexpected status: 500, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", host: "adduser.myapp.com"
2023/07/26 12:23:38 [warn] 233#233: *29 using uninitialized "upstream_authelia" variable, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", host: "adduser.myapp.com"
2023/07/26 12:23:38 [error] 233#233: *29 invalid URL prefix in "", client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", host: "adduser.myapp.com"
2023/07/26 12:23:38 [error] 233#233: *29 auth request unexpected status: 500, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", host: "adduser.myapp.com"
2023/07/26 12:23:38 [warn] 233#233: *30 using uninitialized "upstream_authelia" variable, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", host: "adduser.myapp.com"
2023/07/26 12:23:38 [error] 233#233: *30 invalid URL prefix in "", client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", host: "adduser.myapp.com"
2023/07/26 12:23:38 [error] 233#233: *30 auth request unexpected status: 500, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", host: "adduser.myapp.com"
2023/07/26 12:27:01 [warn] 235#235: *7 using uninitialized "upstream_authelia" variable, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", host: "adduser.myapp.com"
2023/07/26 12:27:01 [error] 235#235: *7 invalid URL prefix in "", client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", host: "adduser.myapp.com"
2023/07/26 12:27:01 [error] 235#235: *7 auth request unexpected status: 500, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", host: "adduser.myapp.com"
2023/07/26 12:27:01 [warn] 235#235: *6 using uninitialized "upstream_authelia" variable, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", host: "adduser.myapp.com"
2023/07/26 12:27:01 [error] 235#235: *6 invalid URL prefix in "", client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", host: "adduser.myapp.com"
2023/07/26 12:27:01 [error] 235#235: *6 auth request unexpected status: 500, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", host: "adduser.myapp.com"
2023/07/26 12:27:02 [warn] 235#235: *8 using uninitialized "upstream_authelia" variable, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", host: "adduser.myapp.com"
2023/07/26 12:27:02 [error] 235#235: *8 invalid URL prefix in "", client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", host: "adduser.myapp.com"
2023/07/26 12:27:02 [error] 235#235: *8 auth request unexpected status: 500, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", host: "adduser.myapp.com"
2023/07/26 12:27:02 [warn] 235#235: *9 using uninitialized "upstream_authelia" variable, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", host: "adduser.myapp.com"
2023/07/26 12:27:02 [error] 235#235: *9 invalid URL prefix in "", client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", host: "adduser.myapp.com"
2023/07/26 12:27:02 [error] 235#235: *9 auth request unexpected status: 500, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", host: "adduser.myapp.com"
2023/07/26 12:27:02 [warn] 235#235: *10 using uninitialized "upstream_authelia" variable, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", host: "adduser.myapp.com"
2023/07/26 12:27:02 [error] 235#235: *10 invalid URL prefix in "", client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", host: "adduser.myapp.com"
2023/07/26 12:27:02 [error] 235#235: *10 auth request unexpected status: 500, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", host: "adduser.myapp.com"
2023/07/26 12:27:02 [warn] 235#235: *11 using uninitialized "upstream_authelia" variable, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", host: "adduser.myapp.com"
2023/07/26 12:27:02 [error] 235#235: *11 invalid URL prefix in "", client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", host: "adduser.myapp.com"
2023/07/26 12:27:02 [error] 235#235: *11 auth request unexpected status: 500, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", host: "adduser.myapp.com"
2023/07/26 12:27:03 [warn] 235#235: *12 using uninitialized "upstream_authelia" variable, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", host: "adduser.myapp.com"
2023/07/26 12:27:03 [error] 235#235: *12 invalid URL prefix in "", client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", host: "adduser.myapp.com"
2023/07/26 12:27:03 [error] 235#235: *12 auth request unexpected status: 500, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", host: "adduser.myapp.com"
2023/07/26 12:27:29 [warn] 235#235: *16 using uninitialized "upstream_authelia" variable, client: 172.21.0.1, server: adduser.myapp.com, request: "POST / HTTP/1.1", subrequest: "/authelia", host: "adduser.myapp.com"
2023/07/26 12:27:29 [error] 235#235: *16 invalid URL prefix in "", client: 172.21.0.1, server: adduser.myapp.com, request: "POST / HTTP/1.1", subrequest: "/authelia", host: "adduser.myapp.com"
2023/07/26 12:27:29 [error] 235#235: *16 auth request unexpected status: 500, client: 172.21.0.1, server: adduser.myapp.com, request: "POST / HTTP/1.1", host: "adduser.myapp.com"
2023/07/26 12:28:34 [warn] 235#235: *21 using uninitialized "upstream_authelia" variable, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", host: "adduser.myapp.com"
2023/07/26 12:28:34 [error] 235#235: *21 invalid URL prefix in "", client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", host: "adduser.myapp.com"
2023/07/26 12:28:34 [error] 235#235: *21 auth request unexpected status: 500, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", host: "adduser.myapp.com"
2023/07/26 12:29:32 [warn] 234#234: *4 using uninitialized "upstream_authelia" variable, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", host: "adduser.myapp.com"
2023/07/26 12:29:32 [error] 234#234: *4 invalid URL prefix in "", client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", host: "adduser.myapp.com"
2023/07/26 12:29:32 [error] 234#234: *4 auth request unexpected status: 500, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", host: "adduser.myapp.com"
2023/07/26 12:29:33 [warn] 234#234: *5 using uninitialized "upstream_authelia" variable, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", host: "adduser.myapp.com"
2023/07/26 12:29:33 [error] 234#234: *5 invalid URL prefix in "", client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", host: "adduser.myapp.com"
2023/07/26 12:29:33 [error] 234#234: *5 auth request unexpected status: 500, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", host: "adduser.myapp.com"
2023/07/26 12:29:58 [warn] 234#234: *6 using uninitialized "upstream_authelia" variable, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", host: "adduser.myapp.com"
2023/07/26 12:29:58 [error] 234#234: *6 invalid URL prefix in "", client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", host: "adduser.myapp.com"
2023/07/26 12:29:58 [error] 234#234: *6 auth request unexpected status: 500, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", host: "adduser.myapp.com"
2023/07/26 12:29:58 [warn] 234#234: *10 using uninitialized "upstream_authelia" variable, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", host: "adduser.myapp.com"
2023/07/26 12:29:58 [error] 234#234: *10 invalid URL prefix in "", client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", host: "adduser.myapp.com"
2023/07/26 12:29:58 [error] 234#234: *10 auth request unexpected status: 500, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", host: "adduser.myapp.com"
2023/07/26 12:29:58 [warn] 234#234: *11 using uninitialized "upstream_authelia" variable, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", host: "adduser.myapp.com"
2023/07/26 12:29:58 [error] 234#234: *11 invalid URL prefix in "", client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", host: "adduser.myapp.com"
2023/07/26 12:29:58 [error] 234#234: *11 auth request unexpected status: 500, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", host: "adduser.myapp.com"
2023/07/26 12:29:59 [warn] 234#234: *12 using uninitialized "upstream_authelia" variable, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", host: "adduser.myapp.com"
2023/07/26 12:29:59 [error] 234#234: *12 invalid URL prefix in "", client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", host: "adduser.myapp.com"
2023/07/26 12:29:59 [error] 234#234: *12 auth request unexpected status: 500, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", host: "adduser.myapp.com"
2023/07/26 12:29:59 [warn] 234#234: *13 using uninitialized "upstream_authelia" variable, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", host: "adduser.myapp.com"
2023/07/26 12:29:59 [error] 234#234: *13 invalid URL prefix in "", client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", host: "adduser.myapp.com"
2023/07/26 12:29:59 [error] 234#234: *13 auth request unexpected status: 500, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", host: "adduser.myapp.com"
2023/07/26 12:29:59 [warn] 234#234: *14 using uninitialized "upstream_authelia" variable, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", host: "adduser.myapp.com"
2023/07/26 12:29:59 [error] 234#234: *14 invalid URL prefix in "", client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", host: "adduser.myapp.com"
2023/07/26 12:29:59 [error] 234#234: *14 auth request unexpected status: 500, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", host: "adduser.myapp.com"
2023/07/26 12:30:00 [warn] 234#234: *15 using uninitialized "upstream_authelia" variable, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", host: "adduser.myapp.com"
2023/07/26 12:30:00 [error] 234#234: *15 invalid URL prefix in "", client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", host: "adduser.myapp.com"
2023/07/26 12:30:00 [error] 234#234: *15 auth request unexpected status: 500, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", host: "adduser.myapp.com"
2023/07/26 12:30:00 [warn] 234#234: *16 using uninitialized "upstream_authelia" variable, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", host: "adduser.myapp.com"
2023/07/26 12:30:00 [error] 234#234: *16 invalid URL prefix in "", client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", host: "adduser.myapp.com"
2023/07/26 12:30:00 [error] 234#234: *16 auth request unexpected status: 500, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", host: "adduser.myapp.com"
2023/07/26 12:30:00 [warn] 234#234: *18 using uninitialized "upstream_authelia" variable, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", host: "adduser.myapp.com"
2023/07/26 12:30:00 [error] 234#234: *18 invalid URL prefix in "", client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", host: "adduser.myapp.com"
2023/07/26 12:30:00 [error] 234#234: *18 auth request unexpected status: 500, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", host: "adduser.myapp.com"
2023/07/26 12:30:00 [warn] 234#234: *17 using uninitialized "upstream_authelia" variable, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", host: "adduser.myapp.com"
2023/07/26 12:30:00 [error] 234#234: *17 invalid URL prefix in "", client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", host: "adduser.myapp.com"
2023/07/26 12:30:00 [error] 234#234: *17 auth request unexpected status: 500, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", host: "adduser.myapp.com"
2023/07/26 12:39:12 [warn] 232#232: *7 using uninitialized "upstream_authelia" variable, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", host: "adduser.myapp.com"
2023/07/26 12:39:12 [error] 232#232: *7 invalid URL prefix in "", client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", host: "adduser.myapp.com"
2023/07/26 12:39:12 [error] 232#232: *7 auth request unexpected status: 500, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", host: "adduser.myapp.com"
2023/07/26 12:39:14 [warn] 232#232: *6 using uninitialized "upstream_authelia" variable, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", host: "adduser.myapp.com"
2023/07/26 12:39:14 [error] 232#232: *6 invalid URL prefix in "", client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", host: "adduser.myapp.com"
2023/07/26 12:39:14 [error] 232#232: *6 auth request unexpected status: 500, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", host: "adduser.myapp.com"
2023/07/26 12:39:14 [warn] 232#232: *8 using uninitialized "upstream_authelia" variable, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", host: "adduser.myapp.com"
2023/07/26 12:39:14 [error] 232#232: *8 invalid URL prefix in "", client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", host: "adduser.myapp.com"
2023/07/26 12:39:14 [error] 232#232: *8 auth request unexpected status: 500, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", host: "adduser.myapp.com"
2023/07/26 12:39:14 [warn] 232#232: *9 using uninitialized "upstream_authelia" variable, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", host: "adduser.myapp.com"
2023/07/26 12:39:14 [error] 232#232: *9 invalid URL prefix in "", client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", host: "adduser.myapp.com"
2023/07/26 12:39:14 [error] 232#232: *9 auth request unexpected status: 500, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", host: "adduser.myapp.com"
2023/07/26 12:41:28 [warn] 234#234: *19 using uninitialized "upstream_authelia" variable, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", host: "adduser.myapp.com"
2023/07/26 12:41:28 [error] 234#234: *19 invalid URL prefix in "", client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", host: "adduser.myapp.com"
2023/07/26 12:41:28 [error] 234#234: *19 auth request unexpected status: 500, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", host: "adduser.myapp.com"
2023/07/26 12:45:18 [warn] 237#237: *4 using uninitialized "upstream_authelia" variable, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", host: "adduser.myapp.com"
2023/07/26 12:45:18 [error] 237#237: *4 invalid URL prefix in "", client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", host: "adduser.myapp.com"
2023/07/26 12:45:18 [error] 237#237: *4 auth request unexpected status: 500, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", host: "adduser.myapp.com"
2023/07/26 12:56:12 [info] 223#223: *4 epoll_wait() reported that client prematurely closed connection, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", host: "adduser.myapp.com"
2023/07/26 12:56:50 [error] 223#223: *3 serverip could not be resolved (110: Operation timed out), client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/26 12:56:50 [error] 223#223: *3 auth request unexpected status: 502 while sending to client, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/26 12:57:30 [error] 223#223: *17 serverip could not be resolved (110: Operation timed out), client: 172.21.0.1, server: adduser.myapp.com, request: "POST / HTTP/1.1", subrequest: "/authelia", host: "adduser.myapp.com"
2023/07/26 12:57:30 [error] 223#223: *17 auth request unexpected status: 502 while sending to client, client: 172.21.0.1, server: adduser.myapp.com, request: "POST / HTTP/1.1", host: "adduser.myapp.com"
2023/07/26 12:59:31 [error] 223#223: *36 serverip could not be resolved (110: Operation timed out), client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/26 12:59:31 [error] 223#223: *36 auth request unexpected status: 502 while sending to client, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/26 13:06:18 [error] 233#233: *5 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", upstream: "http://127.0.0.1:9091/api/verify", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/26 13:06:18 [warn] 233#233: *5 upstream server temporarily disabled while connecting to upstream, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", upstream: "http://127.0.0.1:9091/api/verify", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/26 13:06:18 [crit] 233#233: *5 connect() to [::1]:9091 failed (99: Cannot assign requested address) while connecting to upstream, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", upstream: "http://[::1]:9091/api/verify", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/26 13:06:18 [warn] 233#233: *5 upstream server temporarily disabled while connecting to upstream, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", upstream: "http://[::1]:9091/api/verify", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/26 13:06:18 [error] 233#233: *5 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", upstream: "http://[::ffff:127.0.0.1]:9091/api/verify", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/26 13:06:18 [warn] 233#233: *5 upstream server temporarily disabled while connecting to upstream, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", upstream: "http://[::ffff:127.0.0.1]:9091/api/verify", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/26 13:06:18 [error] 233#233: *5 auth request unexpected status: 502 while sending to client, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/26 13:07:43 [error] 253#253: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", upstream: "http://127.0.0.1:9091/api/verify", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/26 13:07:43 [warn] 253#253: *3 upstream server temporarily disabled while connecting to upstream, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", upstream: "http://127.0.0.1:9091/api/verify", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/26 13:07:43 [crit] 253#253: *3 connect() to [::1]:9091 failed (99: Cannot assign requested address) while connecting to upstream, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", upstream: "http://[::1]:9091/api/verify", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/26 13:07:43 [warn] 253#253: *3 upstream server temporarily disabled while connecting to upstream, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", upstream: "http://[::1]:9091/api/verify", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/26 13:07:43 [error] 253#253: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", upstream: "http://[::ffff:127.0.0.1]:9091/api/verify", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/26 13:07:43 [warn] 253#253: *3 upstream server temporarily disabled while connecting to upstream, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", upstream: "http://[::ffff:127.0.0.1]:9091/api/verify", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/26 13:07:43 [error] 253#253: *3 auth request unexpected status: 502 while sending to client, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/26 13:08:07 [info] 250#250: *4 epoll_wait() reported that client prematurely closed connection, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/26 13:08:08 [error] 253#253: *12 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", upstream: "http://127.0.0.1:9091/api/verify", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/26 13:08:08 [warn] 253#253: *12 upstream server temporarily disabled while connecting to upstream, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", upstream: "http://127.0.0.1:9091/api/verify", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/26 13:08:08 [crit] 253#253: *12 connect() to [::1]:9091 failed (99: Cannot assign requested address) while connecting to upstream, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", upstream: "http://[::1]:9091/api/verify", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/26 13:08:08 [warn] 253#253: *12 upstream server temporarily disabled while connecting to upstream, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", upstream: "http://[::1]:9091/api/verify", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/26 13:08:08 [error] 253#253: *12 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", upstream: "http://[::ffff:127.0.0.1]:9091/api/verify", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/26 13:08:08 [warn] 253#253: *12 upstream server temporarily disabled while connecting to upstream, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", upstream: "http://[::ffff:127.0.0.1]:9091/api/verify", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/26 13:08:08 [error] 253#253: *12 auth request unexpected status: 502 while sending to client, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/26 13:09:32 [error] 253#253: *25 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", upstream: "http://127.0.0.1:9091/api/verify", host: "adduser.myapp.com"
2023/07/26 13:09:32 [warn] 253#253: *25 upstream server temporarily disabled while connecting to upstream, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", upstream: "http://127.0.0.1:9091/api/verify", host: "adduser.myapp.com"
2023/07/26 13:09:32 [crit] 253#253: *25 connect() to [::1]:9091 failed (99: Cannot assign requested address) while connecting to upstream, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", upstream: "http://[::1]:9091/api/verify", host: "adduser.myapp.com"
2023/07/26 13:09:32 [warn] 253#253: *25 upstream server temporarily disabled while connecting to upstream, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", upstream: "http://[::1]:9091/api/verify", host: "adduser.myapp.com"
2023/07/26 13:09:32 [error] 253#253: *25 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", upstream: "http://[::ffff:127.0.0.1]:9091/api/verify", host: "adduser.myapp.com"
2023/07/26 13:09:32 [warn] 253#253: *25 upstream server temporarily disabled while connecting to upstream, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", upstream: "http://[::ffff:127.0.0.1]:9091/api/verify", host: "adduser.myapp.com"
2023/07/26 13:09:32 [error] 253#253: *25 auth request unexpected status: 502 while sending to client, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", host: "adduser.myapp.com"
2023/07/26 13:10:56 [error] 253#253: *36 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", upstream: "http://127.0.0.1:9091/api/verify", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/26 13:10:56 [warn] 253#253: *36 upstream server temporarily disabled while connecting to upstream, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", upstream: "http://127.0.0.1:9091/api/verify", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/26 13:10:56 [crit] 253#253: *36 connect() to [::1]:9091 failed (99: Cannot assign requested address) while connecting to upstream, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", upstream: "http://[::1]:9091/api/verify", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/26 13:10:56 [warn] 253#253: *36 upstream server temporarily disabled while connecting to upstream, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", upstream: "http://[::1]:9091/api/verify", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/26 13:10:56 [error] 253#253: *36 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", upstream: "http://[::ffff:127.0.0.1]:9091/api/verify", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/26 13:10:56 [warn] 253#253: *36 upstream server temporarily disabled while connecting to upstream, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", upstream: "http://[::ffff:127.0.0.1]:9091/api/verify", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/26 13:10:56 [error] 253#253: *36 auth request unexpected status: 502 while sending to client, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/26 13:10:58 [error] 250#250: *35 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", upstream: "http://127.0.0.1:9091/api/verify", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/26 13:10:58 [warn] 250#250: *35 upstream server temporarily disabled while connecting to upstream, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", upstream: "http://127.0.0.1:9091/api/verify", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/26 13:10:58 [crit] 250#250: *35 connect() to [::1]:9091 failed (99: Cannot assign requested address) while connecting to upstream, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", upstream: "http://[::1]:9091/api/verify", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/26 13:10:58 [warn] 250#250: *35 upstream server temporarily disabled while connecting to upstream, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", upstream: "http://[::1]:9091/api/verify", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/26 13:10:58 [error] 250#250: *35 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", upstream: "http://[::ffff:127.0.0.1]:9091/api/verify", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/26 13:10:58 [warn] 250#250: *35 upstream server temporarily disabled while connecting to upstream, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", upstream: "http://[::ffff:127.0.0.1]:9091/api/verify", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/26 13:10:58 [error] 250#250: *35 auth request unexpected status: 502 while sending to client, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/26 13:11:10 [error] 253#253: *40 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", upstream: "http://127.0.0.1:9091/api/verify", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/26 13:11:10 [warn] 253#253: *40 upstream server temporarily disabled while connecting to upstream, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", upstream: "http://127.0.0.1:9091/api/verify", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/26 13:11:10 [crit] 253#253: *40 connect() to [::1]:9091 failed (99: Cannot assign requested address) while connecting to upstream, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", upstream: "http://[::1]:9091/api/verify", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/26 13:11:10 [warn] 253#253: *40 upstream server temporarily disabled while connecting to upstream, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", upstream: "http://[::1]:9091/api/verify", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/26 13:11:10 [error] 253#253: *40 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", upstream: "http://[::ffff:127.0.0.1]:9091/api/verify", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/26 13:11:10 [warn] 253#253: *40 upstream server temporarily disabled while connecting to upstream, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", upstream: "http://[::ffff:127.0.0.1]:9091/api/verify", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/26 13:11:10 [error] 253#253: *40 auth request unexpected status: 502 while sending to client, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/26 13:11:13 [error] 253#253: *44 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", upstream: "http://127.0.0.1:9091/api/verify", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/26 13:11:13 [warn] 253#253: *44 upstream server temporarily disabled while connecting to upstream, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", upstream: "http://127.0.0.1:9091/api/verify", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/26 13:11:13 [error] 253#253: *44 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", upstream: "http://[::ffff:127.0.0.1]:9091/api/verify", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/26 13:11:13 [warn] 253#253: *44 upstream server temporarily disabled while connecting to upstream, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", upstream: "http://[::ffff:127.0.0.1]:9091/api/verify", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/26 13:11:13 [crit] 253#253: *44 connect() to [::1]:9091 failed (99: Cannot assign requested address) while connecting to upstream, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", upstream: "http://[::1]:9091/api/verify", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/26 13:11:13 [warn] 253#253: *44 upstream server temporarily disabled while connecting to upstream, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", upstream: "http://[::1]:9091/api/verify", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/26 13:11:13 [error] 253#253: *44 auth request unexpected status: 502 while sending to client, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/26 13:11:17 [crit] 253#253: *48 connect() to [::1]:9091 failed (99: Cannot assign requested address) while connecting to upstream, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", upstream: "http://[::1]:9091/api/verify", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/26 13:11:17 [warn] 253#253: *48 upstream server temporarily disabled while connecting to upstream, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", upstream: "http://[::1]:9091/api/verify", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/26 13:11:17 [error] 253#253: *48 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", upstream: "http://[::ffff:127.0.0.1]:9091/api/verify", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/26 13:11:17 [warn] 253#253: *48 upstream server temporarily disabled while connecting to upstream, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", upstream: "http://[::ffff:127.0.0.1]:9091/api/verify", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/26 13:11:17 [error] 253#253: *48 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", upstream: "http://127.0.0.1:9091/api/verify", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/26 13:11:17 [warn] 253#253: *48 upstream server temporarily disabled while connecting to upstream, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", upstream: "http://127.0.0.1:9091/api/verify", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/26 13:11:17 [error] 253#253: *48 auth request unexpected status: 502 while sending to client, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/26 13:11:17 [error] 253#253: *52 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", upstream: "http://[::ffff:127.0.0.1]:9091/api/verify", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/26 13:11:17 [warn] 253#253: *52 upstream server temporarily disabled while connecting to upstream, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", upstream: "http://[::ffff:127.0.0.1]:9091/api/verify", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/26 13:11:17 [crit] 253#253: *52 connect() to [::1]:9091 failed (99: Cannot assign requested address) while connecting to upstream, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", upstream: "http://[::1]:9091/api/verify", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/26 13:11:17 [warn] 253#253: *52 upstream server temporarily disabled while connecting to upstream, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", upstream: "http://[::1]:9091/api/verify", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/26 13:11:17 [error] 253#253: *52 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", upstream: "http://127.0.0.1:9091/api/verify", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/26 13:11:17 [warn] 253#253: *52 upstream server temporarily disabled while connecting to upstream, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", upstream: "http://127.0.0.1:9091/api/verify", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/26 13:11:17 [error] 253#253: *52 auth request unexpected status: 502 while sending to client, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/26 13:11:18 [error] 253#253: *56 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", upstream: "http://127.0.0.1:9091/api/verify", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/26 13:11:18 [warn] 253#253: *56 upstream server temporarily disabled while connecting to upstream, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", upstream: "http://127.0.0.1:9091/api/verify", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/26 13:11:18 [error] 253#253: *56 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", upstream: "http://[::ffff:127.0.0.1]:9091/api/verify", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/26 13:11:18 [warn] 253#253: *56 upstream server temporarily disabled while connecting to upstream, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", upstream: "http://[::ffff:127.0.0.1]:9091/api/verify", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/26 13:11:18 [crit] 253#253: *56 connect() to [::1]:9091 failed (99: Cannot assign requested address) while connecting to upstream, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", upstream: "http://[::1]:9091/api/verify", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/26 13:11:18 [warn] 253#253: *56 upstream server temporarily disabled while connecting to upstream, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", upstream: "http://[::1]:9091/api/verify", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/26 13:11:18 [error] 253#253: *56 auth request unexpected status: 502 while sending to client, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/26 13:11:23 [error] 253#253: *60 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", upstream: "http://127.0.0.1:9091/api/verify", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/26 13:11:23 [warn] 253#253: *60 upstream server temporarily disabled while connecting to upstream, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", upstream: "http://127.0.0.1:9091/api/verify", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/26 13:11:23 [crit] 253#253: *60 connect() to [::1]:9091 failed (99: Cannot assign requested address) while connecting to upstream, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", upstream: "http://[::1]:9091/api/verify", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/26 13:11:23 [warn] 253#253: *60 upstream server temporarily disabled while connecting to upstream, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", upstream: "http://[::1]:9091/api/verify", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/26 13:11:23 [error] 253#253: *60 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", upstream: "http://[::ffff:127.0.0.1]:9091/api/verify", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/26 13:11:23 [warn] 253#253: *60 upstream server temporarily disabled while connecting to upstream, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", upstream: "http://[::ffff:127.0.0.1]:9091/api/verify", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/26 13:11:23 [error] 253#253: *60 auth request unexpected status: 502 while sending to client, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/26 13:16:30 [error] 217#217: *12 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", upstream: "http://127.0.0.1:9091/api/verify", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/26 13:16:30 [warn] 217#217: *12 upstream server temporarily disabled while connecting to upstream, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", upstream: "http://127.0.0.1:9091/api/verify", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/26 13:16:30 [crit] 217#217: *12 connect() to [::1]:9091 failed (99: Cannot assign requested address) while connecting to upstream, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", upstream: "http://[::1]:9091/api/verify", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/26 13:16:30 [warn] 217#217: *12 upstream server temporarily disabled while connecting to upstream, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", upstream: "http://[::1]:9091/api/verify", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/26 13:16:30 [error] 217#217: *12 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", upstream: "http://[::ffff:127.0.0.1]:9091/api/verify", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/26 13:16:30 [warn] 217#217: *12 upstream server temporarily disabled while connecting to upstream, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", upstream: "http://[::ffff:127.0.0.1]:9091/api/verify", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/26 13:16:30 [error] 217#217: *12 auth request unexpected status: 502 while sending to client, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/26 13:31:32 [error] 238#238: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", upstream: "http://172.21.0.2:9091/api/verify", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/26 13:31:32 [error] 238#238: *3 auth request unexpected status: 502 while sending to client, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/26 13:43:24 [error] 268#268: *10 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", upstream: "http://172.21.0.2:9091/api/verify", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/26 13:43:24 [error] 268#268: *10 auth request unexpected status: 502 while sending to client, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/26 13:50:44 [error] 227#227: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", upstream: "http://172.21.0.2:9091/api/verify", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/26 13:50:44 [error] 227#227: *4 auth request unexpected status: 502 while sending to client, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/26 13:53:41 [error] 224#224: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", upstream: "http://172.21.0.2:9091/api/verify?rd=https://dockerhost.company.local:9091/", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/26 13:53:41 [error] 224#224: *2 auth request unexpected status: 502 while sending to client, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/26 13:58:31 [error] 224#224: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", upstream: "http://172.21.0.2:9091/api/verify?rd=https://dockerhost.company.local:9091/", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/26 13:58:31 [error] 224#224: *4 auth request unexpected status: 502 while sending to client, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/26 13:58:34 [error] 226#226: *5 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", upstream: "http://172.21.0.2:9091/api/verify?rd=https://dockerhost.company.local:9091/", host: "adduser.myapp.com"
2023/07/26 13:58:34 [error] 226#226: *5 auth request unexpected status: 502 while sending to client, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", host: "adduser.myapp.com"
2023/07/26 19:36:28 [info] 440#440: *38 client 172.21.0.1 closed keepalive connection
2023/07/26 19:36:53 [info] 440#440: *43 client 172.21.0.1 closed keepalive connection
2023/07/27 08:24:23 [info] 216#216: *46 client 172.21.0.1 closed keepalive connection
2023/07/27 08:34:02 [info] 216#216: *76 client 172.21.0.1 closed keepalive connection
2023/07/27 08:34:25 [info] 216#216: *80 client 172.21.0.1 closed keepalive connection
2023/07/27 13:41:01 [error] 239#239: *4 open() "/etc/nginx/nginx/html/authelia" failed (2: No such file or directory), client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", subrequest: "/authelia", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/27 13:41:01 [error] 239#239: *4 auth request unexpected status: 404, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/27 17:40:39 [alert] 486#486: *1264 512 worker_connections are not enough while connecting to upstream, client: 127.0.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:80/", host: "adduser.myapp.com"
2023/07/27 17:41:01 [alert] 486#486: *3016 512 worker_connections are not enough while connecting to upstream, client: 127.0.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:80/", host: "adduser.myapp.com"
2023/07/27 17:42:23 [alert] 486#486: *4096 512 worker_connections are not enough while connecting to upstream, client: 127.0.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:80/", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/27 17:43:55 [alert] 486#486: *5543 512 worker_connections are not enough while connecting to upstream, client: 127.0.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:80/", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/27 17:50:23 [alert] 486#486: *6489 512 worker_connections are not enough while connecting to upstream, client: 127.0.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:80/", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/27 17:51:14 [alert] 486#486: *7442 512 worker_connections are not enough while connecting to upstream, client: 127.0.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:80/", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/27 17:51:59 [error] 487#487: *9198 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 127.0.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:80/", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/27 17:51:59 [alert] 486#486: *9242 512 worker_connections are not enough while connecting to upstream, client: 127.0.0.1, server: adduser.myapp.com, request: "GET /auth HTTP/1.1", upstream: "http://127.0.0.1:80/auth", host: "adduser.myapp.com"
2023/07/27 17:52:21 [alert] 486#486: *10140 512 worker_connections are not enough while connecting to upstream, client: 127.0.0.1, server: adduser.myapp.com, request: "GET /auth HTTP/1.1", upstream: "http://127.0.0.1:80/auth", host: "adduser.myapp.com"
2023/07/27 17:53:47 [alert] 486#486: *11061 512 worker_connections are not enough while connecting to upstream, client: 127.0.0.1, server: adduser.myapp.com, request: "GET /?rd=http://dockerhost.company.local:8089/; HTTP/1.1", upstream: "http://127.0.0.1:80/?rd=http://dockerhost.company.local:8089/;", host: "adduser.myapp.com", referrer: "http://auth.myapp.com/"
2023/07/27 17:54:35 [alert] 486#486: *12000 512 worker_connections are not enough while connecting to upstream, client: 127.0.0.1, server: adduser.myapp.com, request: "GET /?rd=http://dockerhost.company.local:8089/; HTTP/1.1", upstream: "http://127.0.0.1:80/?rd=http://dockerhost.company.local:8089/;", host: "adduser.myapp.com", referrer: "http://auth.myapp.com/"
2023/07/27 17:55:30 [alert] 486#486: *12897 512 worker_connections are not enough while connecting to upstream, client: 127.0.0.1, server: adduser.myapp.com, request: "GET /?rd=http://dockerhost.company.local:8089/; HTTP/1.1", upstream: "http://127.0.0.1:80/?rd=http://dockerhost.company.local:8089/;", host: "adduser.myapp.com", referrer: "http://auth.myapp.com/"
2023/07/27 17:57:09 [alert] 486#486: *13786 512 worker_connections are not enough while connecting to upstream, client: 127.0.0.1, server: adduser.myapp.com, request: "GET /?rd=http://dockerhost.company.local:8089/; HTTP/1.1", upstream: "http://127.0.0.1:80/?rd=http://dockerhost.company.local:8089/;", host: "adduser.myapp.com"
2023/07/27 17:57:28 [alert] 486#486: *14717 512 worker_connections are not enough while connecting to upstream, client: 127.0.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:80/", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/27 17:58:51 [alert] 486#486: *15662 512 worker_connections are not enough while connecting to upstream, client: 127.0.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:80/", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/27 20:13:16 [error] 217#217: *8 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:8089/v1/Adduser", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/27 20:13:16 [warn] 217#217: *8 upstream server temporarily disabled while connecting to upstream, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:8089/v1/Adduser", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/27 20:13:16 [error] 217#217: *8 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:8089/v1/Adduser", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/27 20:13:16 [warn] 217#217: *8 upstream server temporarily disabled while connecting to upstream, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:8089/v1/Adduser", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/27 21:15:33 [error] 233#233: *886 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 127.0.0.1, server: adduser.myapp.com, request: "GET /auth HTTP/1.1", upstream: "http://127.0.0.1:80/auth", host: "adduser.myapp.com"
2023/07/27 21:15:41 [error] 233#233: *1460 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 127.0.0.1, server: adduser.myapp.com, request: "GET /auth HTTP/1.1", upstream: "http://127.0.0.1:80/auth", host: "adduser.myapp.com"
2023/07/27 21:15:41 [error] 233#233: *2114 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 127.0.0.1, server: adduser.myapp.com, request: "GET /auth HTTP/1.1", upstream: "http://127.0.0.1:80/auth", host: "adduser.myapp.com"
2023/07/27 21:16:04 [error] 233#233: *2857 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 127.0.0.1, server: adduser.myapp.com, request: "GET /auth HTTP/1.1", upstream: "http://127.0.0.1:80/auth", host: "adduser.myapp.com"
2023/07/27 21:22:43 [alert] 232#232: *3825 512 worker_connections are not enough while connecting to upstream, client: 127.0.0.1, server: adduser.myapp.com, request: "GET /authelia HTTP/1.1", upstream: "http://127.0.0.1:80/authelia", host: "adduser.myapp.com"
2023/07/27 21:24:12 [alert] 232#232: *4433 512 worker_connections are not enough while connecting to upstream, client: 127.0.0.1, server: adduser.myapp.com, request: "GET /authelia HTTP/1.1", upstream: "http://127.0.0.1:80/authelia", host: "adduser.myapp.com"
2023/07/27 21:24:13 [alert] 232#232: *5153 512 worker_connections are not enough while connecting to upstream, client: 127.0.0.1, server: adduser.myapp.com, request: "GET /authelia HTTP/1.1", upstream: "http://127.0.0.1:80/authelia", host: "adduser.myapp.com"
2023/07/27 21:24:13 [alert] 232#232: *5765 512 worker_connections are not enough while connecting to upstream, client: 127.0.0.1, server: adduser.myapp.com, request: "GET /authelia HTTP/1.1", upstream: "http://127.0.0.1:80/authelia", host: "adduser.myapp.com"
2023/07/27 21:24:14 [alert] 232#232: *6646 512 worker_connections are not enough while connecting to upstream, client: 127.0.0.1, server: adduser.myapp.com, request: "GET /authelia HTTP/1.1", upstream: "http://127.0.0.1:80/authelia", host: "adduser.myapp.com"
2023/07/27 21:24:14 [error] 234#234: *7521 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 127.0.0.1, server: adduser.myapp.com, request: "GET /authelia HTTP/1.1", upstream: "http://127.0.0.1:80/authelia", host: "adduser.myapp.com"
2023/07/27 21:24:16 [alert] 232#232: *8173 512 worker_connections are not enough while connecting to upstream, client: 127.0.0.1, server: adduser.myapp.com, request: "GET /authelia HTTP/1.1", upstream: "http://127.0.0.1:80/authelia", host: "adduser.myapp.com"
2023/07/27 21:24:16 [alert] 233#233: *9217 512 worker_connections are not enough while connecting to upstream, client: 127.0.0.1, server: adduser.myapp.com, request: "GET /authelia HTTP/1.1", upstream: "http://127.0.0.1:80/authelia", host: "adduser.myapp.com"
2023/07/27 21:24:16 [error] 235#235: *10219 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 127.0.0.1, server: adduser.myapp.com, request: "GET /authelia HTTP/1.1", upstream: "http://127.0.0.1:80/authelia", host: "adduser.myapp.com"
2023/07/27 21:29:01 [alert] 232#232: *10848 512 worker_connections are not enough while connecting to upstream, client: 127.0.0.1, server: adduser.myapp.com, request: "GET /auth HTTP/1.1", upstream: "http://127.0.0.1:80/auth", host: "adduser.myapp.com"
2023/07/27 21:31:42 [alert] 232#232: *11504 512 worker_connections are not enough while connecting to upstream, client: 127.0.0.1, server: adduser.myapp.com, request: "GET /auth HTTP/1.1", upstream: "http://127.0.0.1:80/auth", host: "adduser.myapp.com"
2023/07/27 21:35:58 [alert] 232#232: *12349 512 worker_connections are not enough while connecting to upstream, client: 127.0.0.1, server: adduser.myapp.com, request: "GET /auth HTTP/1.1", upstream: "http://127.0.0.1:80/auth", host: "adduser.myapp.com"
2023/07/27 21:35:59 [error] 235#235: *13285 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 127.0.0.1, server: adduser.myapp.com, request: "GET /auth HTTP/1.1", upstream: "http://127.0.0.1:80/auth", host: "adduser.myapp.com"
2023/07/27 21:35:59 [alert] 232#232: *13901 512 worker_connections are not enough while connecting to upstream, client: 127.0.0.1, server: adduser.myapp.com, request: "GET /auth HTTP/1.1", upstream: "http://127.0.0.1:80/auth", host: "adduser.myapp.com"
2023/07/27 21:53:21 [alert] 232#232: *14841 512 worker_connections are not enough while connecting to upstream, client: 127.0.0.1, server: adduser.myapp.com, request: "GET /authelia HTTP/1.1", upstream: "http://127.0.0.1:80/authelia", host: "adduser.myapp.com"
2023/07/27 21:54:44 [alert] 232#232: *15547 512 worker_connections are not enough while connecting to upstream, client: 127.0.0.1, server: adduser.myapp.com, request: "GET /authelia HTTP/1.1", upstream: "http://127.0.0.1:80/authelia", host: "adduser.myapp.com"
2023/07/27 23:22:49 [error] 271#271: *16 auth request unexpected status: 404 while sending to client, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", host: "adduser.myapp.com"
2023/07/27 23:22:50 [error] 271#271: *21 auth request unexpected status: 404 while sending to client, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", host: "adduser.myapp.com"
2023/07/27 23:23:09 [error] 271#271: *36 auth request unexpected status: 404 while sending to client, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", host: "adduser.myapp.com"
2023/07/27 23:23:47 [error] 271#271: *38 auth request unexpected status: 404 while sending to client, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", host: "adduser.myapp.com"
2023/07/27 23:23:48 [error] 271#271: *42 auth request unexpected status: 404 while sending to client, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", host: "adduser.myapp.com"
2023/07/27 23:23:48 [error] 271#271: *44 auth request unexpected status: 404 while sending to client, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", host: "adduser.myapp.com"
2023/07/27 23:23:48 [error] 271#271: *46 auth request unexpected status: 404 while sending to client, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", host: "adduser.myapp.com"
2023/07/27 23:23:50 [error] 271#271: *48 auth request unexpected status: 404 while sending to client, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", host: "adduser.myapp.com"
2023/07/27 23:23:56 [error] 271#271: *50 auth request unexpected status: 404 while sending to client, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/27 23:24:06 [error] 271#271: *54 auth request unexpected status: 404 while sending to client, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/27 23:24:53 [error] 271#271: *56 auth request unexpected status: 404 while sending to client, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/27 23:31:32 [error] 273#273: *108 auth request unexpected status: 404 while sending to client, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/27 23:32:48 [error] 271#271: *137 auth request unexpected status: 404 while sending to client, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/27 23:32:48 [error] 271#271: *136 auth request unexpected status: 404 while sending to client, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/27 23:32:49 [error] 271#271: *139 auth request unexpected status: 404 while sending to client, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/27 23:32:50 [error] 271#271: *141 auth request unexpected status: 404 while sending to client, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/27 23:34:33 [error] 271#271: *143 auth request unexpected status: 404 while sending to client, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", host: "adduser.myapp.com"
2023/07/27 23:36:01 [error] 273#273: *194 auth request unexpected status: 404 while sending to client, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", host: "adduser.myapp.com"
2023/07/27 23:36:02 [error] 271#271: *195 auth request unexpected status: 404 while sending to client, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", host: "adduser.myapp.com"
2023/07/27 23:36:11 [error] 271#271: *197 auth request unexpected status: 404 while sending to client, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/27 23:37:04 [error] 271#271: *201 auth request unexpected status: 404 while sending to client, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/27 23:37:05 [error] 271#271: *207 auth request unexpected status: 404 while sending to client, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/27 23:37:06 [error] 271#271: *209 auth request unexpected status: 404 while sending to client, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/27 23:37:06 [error] 271#271: *213 auth request unexpected status: 404 while sending to client, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/27 23:37:06 [error] 271#271: *215 auth request unexpected status: 404 while sending to client, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/27 23:37:07 [error] 271#271: *217 auth request unexpected status: 404 while sending to client, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/27 23:37:07 [error] 271#271: *220 auth request unexpected status: 404 while sending to client, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/27 23:37:07 [error] 271#271: *223 auth request unexpected status: 404 while sending to client, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/27 23:37:07 [error] 271#271: *222 auth request unexpected status: 404 while sending to client, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/1.1", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/28 08:28:06 [error] 238#238: *112 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: adduser.myapp.com, request: "GET /auth HTTP/1.1", upstream: "http://172.21.0.6:8088/v1/transfer_user", host: "adduser.myapp.com"
2023/07/28 08:30:18 [error] 238#238: *147 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: adduser.myapp.com, request: "GET /auth HTTP/1.1", upstream: "http://172.21.0.6:8088/v1/transfer_user", host: "adduser.myapp.com"
2023/07/28 08:30:42 [error] 238#238: *147 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: adduser.myapp.com, request: "GET /auth HTTP/1.1", upstream: "http://172.21.0.6:8088/v1/transfer_user", host: "adduser.myapp.com", referrer: "http://auth.myapp.com/"
2023/07/28 08:48:12 [error] 238#238: *261 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: adduser.myapp.com, request: "GET /auth HTTP/1.1", upstream: "http://172.21.0.6:8088/v1/transfer_user", host: "adduser.myapp.com", referrer: "http://auth.myapp.com/"
2023/07/28 08:48:13 [error] 238#238: *261 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: adduser.myapp.com, request: "GET /auth HTTP/1.1", upstream: "http://172.21.0.6:8088/v1/transfer_user", host: "adduser.myapp.com"
2023/07/28 08:48:14 [error] 238#238: *261 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: adduser.myapp.com, request: "GET /auth HTTP/1.1", upstream: "http://172.21.0.6:8088/v1/transfer_user", host: "adduser.myapp.com"
2023/07/28 08:48:14 [error] 238#238: *261 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: adduser.myapp.com, request: "GET /auth HTTP/1.1", upstream: "http://172.21.0.6:8088/v1/transfer_user", host: "adduser.myapp.com"
2023/07/28 08:48:14 [error] 238#238: *261 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: adduser.myapp.com, request: "GET /auth HTTP/1.1", upstream: "http://172.21.0.6:8088/v1/transfer_user", host: "adduser.myapp.com"
2023/07/28 08:56:15 [error] 8430#8430: *347 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: adduser.myapp.com, request: "GET /auth HTTP/1.1", upstream: "http://172.21.0.6:8088/v1/transfer_user", host: "adduser.myapp.com", referrer: "http://auth.myapp.com/"
2023/07/28 10:52:48 [warn] 214#214: *17 using uninitialized "upstream_authelia" variable, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/2.0", subrequest: "/authelia", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/28 10:52:48 [error] 214#214: *17 invalid URL prefix in "", client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/2.0", subrequest: "/authelia", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/28 10:52:48 [error] 214#214: *17 auth request unexpected status: 500, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/2.0", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/28 10:53:09 [warn] 214#214: *17 using uninitialized "upstream_authelia" variable, client: 172.21.0.1, server: adduser.myapp.com, request: "GET /auth HTTP/2.0", subrequest: "/authelia", host: "adduser.myapp.com"
2023/07/28 10:53:09 [error] 214#214: *17 invalid URL prefix in "", client: 172.21.0.1, server: adduser.myapp.com, request: "GET /auth HTTP/2.0", subrequest: "/authelia", host: "adduser.myapp.com"
2023/07/28 10:53:09 [error] 214#214: *17 auth request unexpected status: 500, client: 172.21.0.1, server: adduser.myapp.com, request: "GET /auth HTTP/2.0", host: "adduser.myapp.com"
2023/07/28 10:55:28 [error] 211#211: *7 SSL_do_handshake() failed (SSL: error:1408F10B:SSL routines:ssl3_get_record:wrong version number) while SSL handshaking to upstream, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/2.0", subrequest: "/authelia", upstream: "https://172.21.0.2:9091/api/verify", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/28 10:55:28 [error] 211#211: *7 auth request unexpected status: 502 while sending to client, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/2.0", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/28 10:55:29 [error] 211#211: *7 SSL_do_handshake() failed (SSL: error:1408F10B:SSL routines:ssl3_get_record:wrong version number) while SSL handshaking to upstream, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/2.0", subrequest: "/authelia", upstream: "https://172.21.0.2:9091/api/verify", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/28 10:55:29 [error] 211#211: *7 auth request unexpected status: 502 while sending to client, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/2.0", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/28 10:55:29 [error] 211#211: *7 SSL_do_handshake() failed (SSL: error:1408F10B:SSL routines:ssl3_get_record:wrong version number) while SSL handshaking to upstream, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/2.0", subrequest: "/authelia", upstream: "https://172.21.0.2:9091/api/verify", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/28 10:55:29 [error] 211#211: *7 auth request unexpected status: 502 while sending to client, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/2.0", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/28 10:55:29 [error] 211#211: *7 SSL_do_handshake() failed (SSL: error:1408F10B:SSL routines:ssl3_get_record:wrong version number) while SSL handshaking to upstream, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/2.0", subrequest: "/authelia", upstream: "https://172.21.0.2:9091/api/verify", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/28 10:55:29 [error] 211#211: *7 auth request unexpected status: 502 while sending to client, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/2.0", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/28 10:55:30 [error] 211#211: *7 SSL_do_handshake() failed (SSL: error:1408F10B:SSL routines:ssl3_get_record:wrong version number) while SSL handshaking to upstream, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/2.0", subrequest: "/authelia", upstream: "https://172.21.0.2:9091/api/verify", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/28 10:55:30 [error] 211#211: *7 auth request unexpected status: 502 while sending to client, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/2.0", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/28 10:55:30 [error] 211#211: *7 SSL_do_handshake() failed (SSL: error:1408F10B:SSL routines:ssl3_get_record:wrong version number) while SSL handshaking to upstream, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/2.0", subrequest: "/authelia", upstream: "https://172.21.0.2:9091/api/verify", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/28 10:55:30 [error] 211#211: *7 auth request unexpected status: 502 while sending to client, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/2.0", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/28 10:55:30 [error] 211#211: *7 SSL_do_handshake() failed (SSL: error:1408F10B:SSL routines:ssl3_get_record:wrong version number) while SSL handshaking to upstream, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/2.0", subrequest: "/authelia", upstream: "https://172.21.0.2:9091/api/verify", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/28 10:55:30 [error] 211#211: *7 auth request unexpected status: 502 while sending to client, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/2.0", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/28 10:55:30 [error] 211#211: *7 SSL_do_handshake() failed (SSL: error:1408F10B:SSL routines:ssl3_get_record:wrong version number) while SSL handshaking to upstream, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/2.0", subrequest: "/authelia", upstream: "https://172.21.0.2:9091/api/verify", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/28 10:55:30 [error] 211#211: *7 auth request unexpected status: 502 while sending to client, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/2.0", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/28 10:55:31 [error] 211#211: *7 SSL_do_handshake() failed (SSL: error:1408F10B:SSL routines:ssl3_get_record:wrong version number) while SSL handshaking to upstream, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/2.0", subrequest: "/authelia", upstream: "https://172.21.0.2:9091/api/verify", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/28 10:55:31 [error] 211#211: *7 auth request unexpected status: 502 while sending to client, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/2.0", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/28 10:55:31 [error] 211#211: *7 SSL_do_handshake() failed (SSL: error:1408F10B:SSL routines:ssl3_get_record:wrong version number) while SSL handshaking to upstream, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/2.0", subrequest: "/authelia", upstream: "https://172.21.0.2:9091/api/verify", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/28 10:55:31 [error] 211#211: *7 auth request unexpected status: 502 while sending to client, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/2.0", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/28 10:56:04 [error] 211#211: *7 SSL_do_handshake() failed (SSL: error:1408F10B:SSL routines:ssl3_get_record:wrong version number) while SSL handshaking to upstream, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/2.0", subrequest: "/authelia", upstream: "https://172.21.0.2:9091/api/verify", host: "adduser.myapp.com", referrer: "http://localhost:81/"
2023/07/28 10:56:04 [error] 211#211: *7 auth request unexpected status: 502 while sending to client, client: 172.21.0.1, server: adduser.myapp.com, request: "GET / HTTP/2.0", host: "adduser.myapp.com", referrer: "http://localhost:81/"
